# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api_instance <- DefaultApi$new()

test_that("CreateBlogBlogPost", {
  # tests for CreateBlogBlogPost
  # base path: http://localhost
  # Create Blog
  # @param post Post 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteBlogBlogIdDelete", {
  # tests for DeleteBlogBlogIdDelete
  # base path: http://localhost
  # Delete Blog
  # @param id AnyType 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadAllBlogsBlogGet", {
  # tests for ReadAllBlogsBlogGet
  # base path: http://localhost
  # Read All Blogs
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadBlogByIdBlogIdIdGet", {
  # tests for ReadBlogByIdBlogIdIdGet
  # base path: http://localhost
  # Read Blog By Id
  # @param id character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ReadBlogBySlugBlogSlugSlugGet", {
  # tests for ReadBlogBySlugBlogSlugSlugGet
  # base path: http://localhost
  # Read Blog By Slug
  # @param slug AnyType 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RootGet", {
  # tests for RootGet
  # base path: http://localhost
  # Root
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("UpdateBlogBlogIdPut", {
  # tests for UpdateBlogBlogIdPut
  # base path: http://localhost
  # Update Blog
  # @param id AnyType 
  # @param post Post 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
