# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidationError")

model_instance <- ValidationError$new()

test_that("loc", {
  # tests for the property `loc` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`loc`, "EXPECTED_RESULT")
})

test_that("msg", {
  # tests for the property `msg` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`msg`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
