# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Post")

model_instance <- Post$new()

test_that("created_utc", {
  # tests for the property `created_utc` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_utc`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("body", {
  # tests for the property `body` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`body`, "EXPECTED_RESULT")
})

test_that("author_id", {
  # tests for the property `author_id` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`author_id`, "EXPECTED_RESULT")
})

test_that("slug", {
  # tests for the property `slug` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`slug`, "EXPECTED_RESULT")
})

test_that("tags", {
  # tests for the property `tags` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`tags`, "EXPECTED_RESULT")
})

test_that("published", {
  # tests for the property `published` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`published`, "EXPECTED_RESULT")
})
