# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DevopsApi")

api_instance <- DevopsApi$new()

test_that("CreateUniqueIndexDevopsIndexesCollectionFieldGet", {
  # tests for CreateUniqueIndexDevopsIndexesCollectionFieldGet
  # base path: http://localhost
  # Create Unique Index
  # @param collection AnyType 
  # @param field AnyType 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
