# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HealthApi")

api_instance <- HealthApi$new()

test_that("CheckHealthHealthGet", {
  # tests for CheckHealthHealthGet
  # base path: http://localhost
  # Check Health
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
