# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UiApi")

api_instance <- UiApi$new()

test_that("GetAllBlogsUiBlogGet", {
  # tests for GetAllBlogsUiBlogGet
  # base path: http://localhost
  # Get All Blogs
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RenderFrontendUiHomepageGet", {
  # tests for RenderFrontendUiHomepageGet
  # base path: http://localhost
  # Render Frontend
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RenderFrontendUiTestGet", {
  # tests for RenderFrontendUiTestGet
  # base path: http://localhost
  # Render Frontend
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
