# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HTTPValidationError")

model_instance <- HTTPValidationError$new()

test_that("detail", {
  # tests for the property `detail` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`detail`, "EXPECTED_RESULT")
})
