# coding: utf-8

"""
    Blog

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_create_blog_blog_post(self) -> None:
        """Test case for create_blog_blog_post

        Create Blog
        """
        pass

    def test_delete_blog_blog_id_delete(self) -> None:
        """Test case for delete_blog_blog_id_delete

        Delete Blog
        """
        pass

    def test_read_all_blogs_blog_get(self) -> None:
        """Test case for read_all_blogs_blog_get

        Read All Blogs
        """
        pass

    def test_read_blog_by_id_blog_id_id_get(self) -> None:
        """Test case for read_blog_by_id_blog_id_id_get

        Read Blog By Id
        """
        pass

    def test_read_blog_by_slug_blog_slug_slug_get(self) -> None:
        """Test case for read_blog_by_slug_blog_slug_slug_get

        Read Blog By Slug
        """
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        Root
        """
        pass

    def test_update_blog_blog_id_put(self) -> None:
        """Test case for update_blog_blog_id_put

        Update Blog
        """
        pass


if __name__ == '__main__':
    unittest.main()
