# coding: utf-8

"""
    Blog

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.ui_api import UiApi


class TestUiApi(unittest.TestCase):
    """UiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UiApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_blogs_ui_blog_get(self) -> None:
        """Test case for get_all_blogs_ui_blog_get

        Get All Blogs
        """
        pass

    def test_render_frontend_ui_homepage_get(self) -> None:
        """Test case for render_frontend_ui_homepage_get

        Render Frontend
        """
        pass

    def test_render_frontend_ui_test_get(self) -> None:
        """Test case for render_frontend_ui_test_get

        Render Frontend
        """
        pass


if __name__ == '__main__':
    unittest.main()
