# coding: utf-8

"""
    Blog

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.post import Post

class TestPost(unittest.TestCase):
    """Post unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Post:
        """Test Post
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Post`
        """
        model = Post()
        if include_optional:
            return Post(
                created_utc = None,
                title = None,
                description = None,
                body = None,
                author_id = None,
                slug = None,
                tags = None,
                published = None
            )
        else:
            return Post(
                title = None,
                description = None,
                body = None,
                author_id = None,
                slug = None,
                tags = None,
                published = None,
        )
        """

    def testPost(self):
        """Test Post"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
