# coding: utf-8

"""
    Blog

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.devops_api import DevopsApi


class TestDevopsApi(unittest.TestCase):
    """DevopsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevopsApi()

    def tearDown(self) -> None:
        pass

    def test_create_unique_index_devops_indexes_collection_field_get(self) -> None:
        """Test case for create_unique_index_devops_indexes_collection_field_get

        Create Unique Index
        """
        pass


if __name__ == '__main__':
    unittest.main()
